name: Release
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_neulintsPassword: ${{ secrets.MAVENPASS }}
          ORG_GRADLE_PROJECT_neulintsUsername: neulints
        run: |
          ./gradlew publish --stacktrace
